<?php
$path=$_SERVER['REQUEST_URI'];
$_GET=array();
if(false!==strpos($path,'?')){
	$query_string=substr($path,1+strpos($path,'?'));
	$path=substr($path,0,strpos($path,'?'));
	$pairs=explode('&',$query_string);
	foreach($pairs as $pair){
		list($name,$value)=explode('=',$pair);
		$_GET[$name]=urldecode($value);
	}
}
$path_ext=false;
if(false!==strrpos($path,'.')){
	$path_ext=substr($path,strrpos($path,'.'));
}
if(!$path_ext){
	if('/'!=substr($path,strlen($path)-1)){
		if($query_string){
			$query_string='?'.$query_string;
		}
		header('location:'.$path.'/'.$query_string);
		exit;
	}
}
$path_array=explode('/',trim($path));

if('go'==$path_array[1]){
	if($_GET['url']){
		header('location:'.$_GET['url']);
	}
	else{
		header('location:/');
	}
	exit;
}
/*
$langs_arr=['rus','eng'];
$default_lang='rus';
$lang=$default_lang;
if(isset($_GET['lang'])){
	if(in_array($_GET['lang'],$langs_arr)){
		setcookie('lang',$_GET['lang'],time()+31536000,'/');//1 year
		header('location:/');
		exit;
	}
}
if(isset($_COOKIE['lang'])){
	if(!in_array($_COOKIE['lang'],$langs_arr)){
		setcookie('lang','',time()+31536000,'/');//clear if lang not exist
		header('location:/');
		exit;
	}
	else{
		$lang=$_COOKIE['lang'];
	}
}
if(!in_array($lang,$langs_arr)){
	$lang=$default_lang;
}
include('index.'.$lang.'.php');
*/
include('index.template.php');